site_name: moonShadow
site_url: https://darkthanblack.github.io/

docs_dir: 'docs'

nav:
    - 'Home': 'index.md'
    - 'objc.io':
        - '介绍': 'objc.io/introduce.md'
        - '#1 更轻量的 ViewControllers':
            - '1.1 更轻量的 ViewControllers': 'objc.io/#1/issue-1-1.md'
            - '1.2 整洁的 Table View 代码': 'objc.io/#1/issue-1-2.md'
    - 'Blogs':
        - '01 记一次人脸识别业务落地': 'blogs/01-faces.md'
    - 'Books':
        - '别让猴子跳回背上——为什么领导没时间，下属没事做？': 'books/book_monky.md'
    - 'About': 'about.md'

theme:
#    name: bootstrap4
#    name: readthedocs
#    name: bootstrap386
    name: material
    favicon: assets/images/logo.png
#    logo: assets/images/logo.png

# 自定义 css
extra_css:
    - 'assets/css/custom.css'

# 自定义 js
extra_javascript:
    - 'assets/js/jquery-3.6.0.min.js'
    - 'assets/js/custom.js'

markdown_extensions:
    - markdown.extensions.attr_list
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde

